In [4]:
import pandas as pd

## Load CSS candidates

Now we have galaxy data, we need to load up the CSS candidate file.

In [25]:
#inFileName = "allpointings_master.dat_NoOverlap"
# inFileName = "data/newallpointingsmaster_26may2021.dat"  # with delimeter ' '
inFileName = "data/inspectedpointings_merged_19Oct2024.csv"  # with delimieter ','

inFile = open(inFileName, 'r')
lines = inFile.readlines()
inFile.close

data = pd.read_csv(inFileName, delimiter=',')

In [26]:
data.columns

Index(['x_wcs', 'y_wcs', 'flux_814', 'flux_475', 'mag_814', 'mag_475', 'color',
       'pointing', 'x', 'y', 'type', 'x_wcs_f', 'y_wcs_f', 'gc_type_f',
       'pointing_f', 'Unnamed: 15'],
      dtype='object')

and then we need to filter for color on CSS in general, and additional filter for UCDs on the tighter color range and luminosity, and outlined in paper 1. Color value are 

- CSS: *color* 0.5 < (F475W − F814W ) < 2.5 and 
- UCD: *color* 1.3 < (F475W − F814W ) < 2.1 and *magnitude* F814W < 22.9 mag

In [16]:
data = data[(data['color'] > 0.5) & (data['color'] < 2.5)]
data_bright = data.loc[data['mag_814']<=25.0].copy()  # take a cut of data where completeness is > ~90% 

# Define the range for UCD 'color' and 'mag_814'
ucd_color_min, ucd_color_max = 1.3, 2.1     #
ucd_mag_814_min, ucd_mag_814_max = 0, 22.9  # should be 0 mag to 22.9 mag

# remove duplicated data
data = data.drop_duplicates()

# Filter the DataFrame
gcs_df = data[(data['color'] <= ucd_color_min) | (data['color'] >= ucd_color_max) |
                 (data['mag_814'] <= ucd_mag_814_min) | (data['mag_814'] >= ucd_mag_814_max)]
ucd_df = data[(data['color'] > ucd_color_min) & (data['color'] < ucd_color_max) &
                 (data['mag_814'] > ucd_mag_814_min) & (data['mag_814'] < ucd_mag_814_max)]

In [32]:
data = data.drop(columns=['x_wcs_f', 'y_wcs_f', 'gc_type_f', 'pointing_f','Unnamed: 15'])

In [27]:
# Define the range for UCD 'color' and 'mag_814'
ucd_color_min, ucd_color_max = 1.3, 2.1     #
ucd_mag_814_min, ucd_mag_814_max = 0, 22.9  # should be 0 mag to 22.9 mag

# remove duplicated data
data = data.drop_duplicates()

data['type'] = "cand"
data.loc[(data['color'] > 0.5) & (data['color'] < 2.5),"type"] = "gc"
data.loc[(data['color'] > ucd_color_min) & (data['color'] < ucd_color_max) &
                 (data['mag_814'] > ucd_mag_814_min) & (data['mag_814'] < ucd_mag_814_max),"type"] = "ucd"

In [30]:
len(data.loc[(data["type"]=="cand")])

724

In [41]:
data = data.sort_values("mag_814", ascending=True).reset_index(drop=True)
data.loc[(data["type"]!="gc") & (data["type"]!="ucd")]

,x_wcs,y_wcs,flux_814,flux_475,mag_814,mag_475,color,pointing,x,y,type
1,195.04579,27.965540,697.964900,0.178462,18.196011,27.825658,9.629647,3-3,1444.346,2880.909,cand
6,194.72036,27.763104,214.543600,35.051880,19.476806,22.092742,2.615936,7-7,2426.813,996.796,cand
7,195.01900,27.987050,206.874500,12.740220,19.516327,23.191578,3.675251,3-3,3148.201,4429.231,cand
13,194.87856,27.884916,116.808300,15.439630,20.136910,22.982928,2.846018,5-5,998.327,2212.464,cand
16,195.22773,28.007409,109.254700,15.477880,20.209494,22.980241,2.770747,2-0,3995.237,2502.300,cand
...,...,...,...,...,...,...,...,...,...,...,...
23345,195.03269,27.973020,0.033727,0.093934,28.985658,28.522462,-0.463196,3-3,2277.393,3419.081,cand
23347,195.01579,27.988940,0.022976,0.065529,29.402425,28.913436,-0.488988,3-3,3351.845,4565.811,cand
23348,195.03345,27.970920,0.022315,0.121167,29.434100,28.246057,-1.188043,3-3,2229.360,3268.153,cand
23349,195.03215,27.968570,0.010858,0.122489,30.216223,28.234277,-1.981946,3-3,2312.130,3098.727,cand
23350,195.02910,27.970960,0.003643,0.132067,31.402080,28.152538,-3.249542,3-3,2505.895,3270.774,cand

In [42]:
data.columns

Index(['x_wcs', 'y_wcs', 'flux_814', 'flux_475', 'mag_814', 'mag_475', 'color',
       'pointing', 'x', 'y', 'type'],
      dtype='object')

## Save to csv file for upload

In [43]:
data.to_csv('data/Coma_css_data_final.csv', index=False, header=False)

In [44]:
inFileName2 = "data/Coma_css_data_final.csv"  # with delimieter ','

# inFile2 = open(inFileName2, 'r')
# lines = inFile2.readlines()
# inFile2.close

data_final = pd.read_csv(inFileName2, delimiter=',', names=['x_wcs', 'y_wcs', 'flux_814', 'flux_475', 'mag_814', 'mag_475', 'color',
       'pointing', 'x', 'y', 'type'])

In [45]:
data_final.columns

Index(['x_wcs', 'y_wcs', 'flux_814', 'flux_475', 'mag_814', 'mag_475', 'color',
       'pointing', 'x', 'y', 'type'],
      dtype='object')

In [46]:
data_final.loc[data_final["pointing"]=="3-3"].head()

,x_wcs,y_wcs,flux_814,flux_475,mag_814,mag_475,color,pointing,x,y,type
1,195.04579,27.96554,697.9649,0.178462,18.196011,27.825658,9.629647,3-3,1444.346,2880.909,cand
7,195.01900,27.98705,206.8745,12.740220,19.516327,23.191578,3.675251,3-3,3148.201,4429.231,cand
10,195.03416,27.97638,143.8035,41.647690,19.911171,21.905543,1.994372,3-3,2183.933,3661.346,ucd
12,195.00411,27.94540,134.5409,49.666800,19.983459,21.714355,1.730896,3-3,4095.246,1431.005,ucd
18,195.02203,27.97665,105.9079,10.900010,20.243274,23.360953,3.117679,3-3,2955.681,3680.973,cand

In [47]:
data_final.head()

,x_wcs,y_wcs,flux_814,flux_475,mag_814,mag_475,color,pointing,x,y,type
0,195.06119,28.041115,2848.1710,877.540100,16.669179,18.596353,1.927173,2-3,1070.320,1674.143,ucd
1,195.04579,27.965540,697.9649,0.178462,18.196011,27.825658,9.629647,3-3,1444.346,2880.909,cand
2,194.90501,27.972215,479.1799,149.100000,18.604348,20.520826,1.916478,3-5,2350.730,2144.226,ucd
3,194.84704,27.912004,413.3326,118.570300,18.764845,20.769580,2.004735,4-6,2556.329,634.693,ucd
4,194.87216,27.849643,250.7268,69.939990,19.307593,21.342706,2.035114,5-5,3525.604,2058.930,ucd